// Generated by `npx @opennextjs/cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import nextWorker from "./.open-next/worker.js";
import { scheduled } from "./src/lib/cms/scheduler";

export default {
  fetch: nextWorker.fetch,
  scheduled
};
